---
title: 'SONA New Design Calibration V9 - 2000ms data'
output:
github_document:
toc: yes
toc_float: yes
---

```{r, message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(plyr)
library(tidyr)
library(ggplot2)
library(stringr)
```


```{r}
dataPath = '/Volumes/Macintosh HD/Users/Pam_sf_wang/Documents/Perceptual_learning_project/Calibration/SONAdata/newDesignV9_001/';

SameDifferentRun01_fnames = list.files(path = dataPath,pattern = "SameDifferentRun01")
SameDifferentRun02_fnames = list.files(path = dataPath,pattern = "SameDifferentRun02")
SameDifferentRun03_fnames = list.files(path = dataPath,pattern = "SameDifferentRun03")
SameDifferentRun04_fnames = list.files(path = dataPath,pattern = "SameDifferentRun04")
SameDifferentRun05_fnames = list.files(path = dataPath,pattern = "SameDifferentRun05")
SameDifferentRun06_fnames = list.files(path = dataPath,pattern = "SameDifferentRun06")
Demo_fnames = list.files(path = dataPath,pattern = "demographics")
Post_fnames = list.files(path = dataPath,pattern = "postsurvey")

data_new_fname = "SONAdata_newDesignV9"
demographic_new_fname = "SONAdemographic_newDesignV9"
postsurvey_new_fname = "SONApostsurvey_newDesignV9"
d_p_thre = 0.5
trial_thre = 77
age_thre = 35
```

## Load data
```{r}
##specify variables
#for behavior information
ic = 1;
completeFnames =list()
totalData = data.frame()

#for demographic information
gender = data.frame()
age = data.frame()
ethnicity= data.frame()
race = data.frame()
subID = data.frame()

#for post survey
Postsurvey=data.frame()
postsubID = data.frame()
confirmationCode = data.frame()
SONAID=data.frame()

##Getting data from online text output
for (ifiles in 1:length(SameDifferentRun01_fnames)){
  ##Getting post-test data    
    for (ifilesDe in 1:length(Post_fnames)){
    if (unlist(strsplit(SameDifferentRun01_fnames[ifiles],"SameDifferentRun01"))[2]==unlist(strsplit(Post_fnames[ifilesDe],"postsurvey"))[2]){   tempPostFile = read.table(paste0(dataPath,Post_fnames[ifilesDe]),header = F)
        ###separate feedback and prolific ID
        if (dim(tempPostFile)[2]>1){
          tempPostFile$y = apply( tempPostFile[,] , 1 , paste , collapse = "" )
          Post_info = unlist(strsplit(as.character(tempPostFile$y), ";"))
          }else{
          Post_info = unlist(strsplit(as.character(tempPostFile$V1), ";"))
          }
          
        Postsurvey[ic,1]=unlist(Post_info[1])
        postsubID[ic,1] = unlist(Post_info[2])
        SONAID[ic,1]=unlist(Post_info[3])
        confirmationCode[ic,1]=unlist(strsplit(SameDifferentRun01_fnames[ifiles],"SameDifferentRun01"))[2]
        }#if 
        }#for
  
   #Getting demo data
  for (ifilesDe in 1:length(Demo_fnames)){
      if (unlist(strsplit(SameDifferentRun01_fnames[ifiles],"SameDifferentRun01"))[2]==unlist(strsplit(Demo_fnames[ifilesDe],"demographics"))[2]){  tempDemoFile = read.table(paste0(dataPath,Demo_fnames[ifilesDe]),header = F)
      Demo_info = unlist(strsplit(as.character(tempDemoFile$V1), ";"))
      gender[ic,1] = unlist(Demo_info[1])
      age[ic,1]=unlist(Demo_info[2])
      ethnicity[ic,1]=unlist(Demo_info[3])
      race[ic,1]=unlist(Demo_info[4])
      subID[ic,1]=unlist(Post_info[2])
      }# if
    }#for
      
  ##############
  tempFile = read.table(paste0(dataPath,SameDifferentRun01_fnames[ifiles]),header = F)
  Trials = unlist(strsplit(as.character(tempFile$V1), ";"))
  
  #if (length(Trials)>10){
    keyNum = data.frame()
    accuracy = data.frame()
    RT = data.frame()
    Fir_img = data.frame()
    Sec_img = data.frame()
    for (i in 1:length(Trials)){
      temp = unlist(strsplit(Trials[i],","));
      keyNum = rbind(keyNum,as.numeric(temp[2]))
      accuracy = rbind(accuracy,as.numeric(temp[4]))
      RT = rbind(RT,as.numeric(temp[5]))
      Fir_img = rbind(Fir_img,as.numeric(temp[6]))
      Sec_img = rbind(Sec_img,as.numeric(temp[7]))
    }
    data = cbind(keyNum,accuracy,RT, Fir_img,Sec_img)
    colnames(data) = c("keys","accuracy", "rt", "Fimg","Simg")
    data = data[-1,]
    data$subID = unlist(Post_info[2]);
    data$trialNum = 1:dim(data)[1];
    data$run = 1;
    
    totalData = rbind(totalData,data)
    completeFnames[ic] =unlist(strsplit(SameDifferentRun01_fnames[ifiles],"SameDifferent"))[2]
    ic = ic+1;
    #}else{}
}#for

```

####Save demographic and post test .csv
```{r}
#demographic information
demographic_information = cbind(gender,age,ethnicity,race,subID)
colnames(demographic_information) = c("Gender","Age","Ethnicity","Race","SubID")
demographic_information$Age = as.numeric(demographic_information$Age)
write.csv(demographic_information, file = paste0(demographic_new_fname,".csv"))
#save post test survey
postsurvey = cbind(Postsurvey,postsubID,SONAID,confirmationCode)
colnames(postsurvey) = c("post_surve","subID","SONAID","confirm_code")
write.csv(postsurvey, file = paste0(postsurvey_new_fname,".csv"))
```


###Run02
```{r}
##Getting data from online text output
for (ifiles in 1:length(SameDifferentRun02_fnames)){
  for (ifilesDe in 1:length(Post_fnames)){
    if (unlist(strsplit(SameDifferentRun02_fnames[ifiles],"SameDifferentRun02"))[2]==unlist(strsplit(Post_fnames[ifilesDe],"postsurvey"))[2]){tempPostFile = read.table(paste0(dataPath,Post_fnames[ifilesDe]),header = F)
        ###separate feedback and prolific ID
        if (dim(tempPostFile)[2]>1){
          tempPostFile$y = apply( tempPostFile[,] , 1 , paste , collapse = "" )
          Post_info = unlist(strsplit(as.character(tempPostFile$y), ";"))
          }else{
          Post_info = unlist(strsplit(as.character(tempPostFile$V1), ";"))
          }
    }}
  
  #####
  tempFile = read.table(paste0(dataPath,SameDifferentRun02_fnames[ifiles]),header = F)
  Trials = unlist(strsplit(as.character(tempFile$V1), ";"))
  
  #if (length(Trials)>10){
    keyNum = data.frame()
    accuracy = data.frame()
    RT = data.frame()
    Fir_img = data.frame()
    Sec_img = data.frame()
    for (i in 1:length(Trials)){
      temp = unlist(strsplit(Trials[i],","));
      keyNum = rbind(keyNum,as.numeric(temp[2]))
      accuracy = rbind(accuracy,as.numeric(temp[4]))
      RT = rbind(RT,as.numeric(temp[5]))
      Fir_img = rbind(Fir_img,as.numeric(temp[6]))
      Sec_img = rbind(Sec_img,as.numeric(temp[7]))
    }
    data = cbind(keyNum,accuracy,RT, Fir_img,Sec_img)
    colnames(data) = c("keys","accuracy", "rt", "Fimg","Simg")
    data = data[-1,]
    data$subID = unlist(Post_info[2]);
    data$trialNum = 1:dim(data)[1];
    data$run = 2;
    
    totalData = rbind(totalData,data)
    #}else{}
}#for

```
  
###Run03
```{r}
runNum = 3;
##Getting data from online text output
for (ifiles in 1:length(SameDifferentRun03_fnames)){
  for (ifilesDe in 1:length(Post_fnames)){
    if (unlist(strsplit(SameDifferentRun03_fnames[ifiles],"SameDifferentRun03"))[2]==unlist(strsplit(Post_fnames[ifilesDe],"postsurvey"))[2]){tempPostFile = read.table(paste0(dataPath,Post_fnames[ifilesDe]),header = F)
        ###separate feedback and prolific ID
        if (dim(tempPostFile)[2]>1){
          tempPostFile$y = apply( tempPostFile[,] , 1 , paste , collapse = "" )
          Post_info = unlist(strsplit(as.character(tempPostFile$y), ";"))
          }else{
          Post_info = unlist(strsplit(as.character(tempPostFile$V1), ";"))
          }
    }}
  #####
  tempFile = read.table(paste0(dataPath,SameDifferentRun03_fnames[ifiles]),header = F)
  Trials = unlist(strsplit(as.character(tempFile$V1), ";"))
  
  #if (length(Trials)>10){
    keyNum = data.frame()
    accuracy = data.frame()
    RT = data.frame()
    Fir_img = data.frame()
    Sec_img = data.frame()
    for (i in 1:length(Trials)){
      temp = unlist(strsplit(Trials[i],","));
      keyNum = rbind(keyNum,as.numeric(temp[2]))
      accuracy = rbind(accuracy,as.numeric(temp[4]))
      RT = rbind(RT,as.numeric(temp[5]))
      Fir_img = rbind(Fir_img,as.numeric(temp[6]))
      Sec_img = rbind(Sec_img,as.numeric(temp[7]))
    }
    data = cbind(keyNum,accuracy,RT, Fir_img,Sec_img)
    colnames(data) = c("keys","accuracy", "rt", "Fimg","Simg")
    data = data[-1,]
    data$subID = unlist(Post_info[2]);
    data$trialNum = 1:dim(data)[1];
    data$run = runNum ;
    
    totalData = rbind(totalData,data)
    #}else{}
}#for

```

###Run04
```{r}
runNum =4;
##Getting data from online text output
for (ifiles in 1:length(SameDifferentRun04_fnames)){
  for (ifilesDe in 1:length(Post_fnames)){
    if (unlist(strsplit(SameDifferentRun04_fnames[ifiles],"SameDifferentRun04"))[2]==unlist(strsplit(Post_fnames[ifilesDe],"postsurvey"))[2]){tempPostFile = read.table(paste0(dataPath,Post_fnames[ifilesDe]),header = F)
        ###separate feedback and prolific ID
        if (dim(tempPostFile)[2]>1){
          tempPostFile$y = apply( tempPostFile[,] , 1 , paste , collapse = "" )
          Post_info = unlist(strsplit(as.character(tempPostFile$y), ";"))
          }else{
          Post_info = unlist(strsplit(as.character(tempPostFile$V1), ";"))
          }
    }}
  #####
  tempFile = read.table(paste0(dataPath,SameDifferentRun04_fnames[ifiles]),header = F)
  Trials = unlist(strsplit(as.character(tempFile$V1), ";"))
  
  #if (length(Trials)>10){
    keyNum = data.frame()
    accuracy = data.frame()
    RT = data.frame()
    Fir_img = data.frame()
    Sec_img = data.frame()
    for (i in 1:length(Trials)){
      temp = unlist(strsplit(Trials[i],","));
      keyNum = rbind(keyNum,as.numeric(temp[2]))
      accuracy = rbind(accuracy,as.numeric(temp[4]))
      RT = rbind(RT,as.numeric(temp[5]))
      Fir_img = rbind(Fir_img,as.numeric(temp[6]))
      Sec_img = rbind(Sec_img,as.numeric(temp[7]))
    }
    data = cbind(keyNum,accuracy,RT, Fir_img,Sec_img)
    colnames(data) = c("keys","accuracy", "rt", "Fimg","Simg")
    data = data[-1,]
    data$subID = unlist(Post_info[2]);
    data$trialNum = 1:dim(data)[1];
    data$run = runNum;
    
    totalData = rbind(totalData,data)
    #}else{}
}#for

```

###Run05
```{r}
runNum = 5;
##Getting data from online text output
for (ifiles in 1:length(SameDifferentRun05_fnames)){
  for (ifilesDe in 1:length(Post_fnames)){
    if (unlist(strsplit(SameDifferentRun05_fnames[ifiles],"SameDifferentRun05"))[2]==unlist(strsplit(Post_fnames[ifilesDe],"postsurvey"))[2]){tempPostFile = read.table(paste0(dataPath,Post_fnames[ifilesDe]),header = F)
        ###separate feedback and prolific ID
        if (dim(tempPostFile)[2]>1){
          tempPostFile$y = apply( tempPostFile[,] , 1 , paste , collapse = "" )
          Post_info = unlist(strsplit(as.character(tempPostFile$y), ";"))
          }else{
          Post_info = unlist(strsplit(as.character(tempPostFile$V1), ";"))
          }
    }}
  
  #####
  tempFile = read.table(paste0(dataPath,SameDifferentRun05_fnames[ifiles]),header = F)
  Trials = unlist(strsplit(as.character(tempFile$V1), ";"))
  
  #if (length(Trials)>10){
    keyNum = data.frame()
    accuracy = data.frame()
    RT = data.frame()
    Fir_img = data.frame()
    Sec_img = data.frame()
    for (i in 1:length(Trials)){
      temp = unlist(strsplit(Trials[i],","));
      keyNum = rbind(keyNum,as.numeric(temp[2]))
      accuracy = rbind(accuracy,as.numeric(temp[4]))
      RT = rbind(RT,as.numeric(temp[5]))
      Fir_img = rbind(Fir_img,as.numeric(temp[6]))
      Sec_img = rbind(Sec_img,as.numeric(temp[7]))
    }
    data = cbind(keyNum,accuracy,RT, Fir_img,Sec_img)
    colnames(data) = c("keys","accuracy", "rt", "Fimg","Simg")
    data = data[-1,]
    data$subID = unlist(Post_info[2]);
    data$trialNum = 1:dim(data)[1];
    data$run = runNum;
    
    totalData = rbind(totalData,data)
    #}else{}
}#for

```

###Run06
```{r}
runNum = 6;
##Getting data from online text output
for (ifiles in 1:length(SameDifferentRun06_fnames)){
  for (ifilesDe in 1:length(Post_fnames)){
    if (unlist(strsplit(SameDifferentRun06_fnames[ifiles],"SameDifferentRun06"))[2]==unlist(strsplit(Post_fnames[ifilesDe],"postsurvey"))[2]){tempPostFile = read.table(paste0(dataPath,Post_fnames[ifilesDe]),header = F)
        ###separate feedback and prolific ID
        if (dim(tempPostFile)[2]>1){
          tempPostFile$y = apply( tempPostFile[,] , 1 , paste , collapse = "" )
          Post_info = unlist(strsplit(as.character(tempPostFile$y), ";"))
          }else{
          Post_info = unlist(strsplit(as.character(tempPostFile$V1), ";"))
          }
    }}
  
  #####
  tempFile = read.table(paste0(dataPath,SameDifferentRun06_fnames[ifiles]),header = F)
  Trials = unlist(strsplit(as.character(tempFile$V1), ";"))
  
  #if (length(Trials)>10){
    keyNum = data.frame()
    accuracy = data.frame()
    RT = data.frame()
    Fir_img = data.frame()
    Sec_img = data.frame()
    for (i in 1:length(Trials)){
      temp = unlist(strsplit(Trials[i],","));
      keyNum = rbind(keyNum,as.numeric(temp[2]))
      accuracy = rbind(accuracy,as.numeric(temp[4]))
      RT = rbind(RT,as.numeric(temp[5]))
      Fir_img = rbind(Fir_img,as.numeric(temp[6]))
      Sec_img = rbind(Sec_img,as.numeric(temp[7]))
    }
    data = cbind(keyNum,accuracy,RT, Fir_img,Sec_img)
    colnames(data) = c("keys","accuracy", "rt", "Fimg","Simg")
    data = data[-1,]
    data$subID = unlist(Post_info[2]);
    data$trialNum = 1:dim(data)[1];
    data$run = runNum;
    
    totalData = rbind(totalData,data)
    #}else{}
}#for

```


####Save totalData .csv
```{r}
write.csv(totalData, file = paste0(data_new_fname,".csv"))
```