---
title: 'Prolific Calibration V323Fs Day01 & Day02'
output:
github_document:
toc: yes
toc_float: yes
---

```{r, message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(plyr)
library(tidyr)
library(ggplot2)
library(stringr)
library(lme4)
library(lmerTest)
library(ez)
```

```{r}
#plotting format
plotformat = theme(plot.title = element_text(face="bold",size = 17,hjust = 0.5),axis.title = element_text(face = "bold",size =15), axis.text.x = element_text(size=12), axis.title.y=element_text(size=14))+theme_bw()

theme_facet = function(base_size = 14, base_family = "Helvetica") {
  # Starts with theme_grey and then modify some parts
  theme_bw(base_size = base_size, base_family = base_family) %+replace%
    theme(
      strip.background = element_blank(),
      strip.text.x = element_text(size = 10),
      strip.text.y = element_text(size = 10),
      axis.text.x = element_blank(),
      axis.text.y = element_text(size=12,hjust=1),
      axis.ticks =  element_blank(), #element_line(colour = "black"), 
      axis.title.x= element_text(size=12),
      axis.title.y= element_text(size=12,angle=90),
      panel.background = element_blank(), 
      panel.border =element_blank(), 
      panel.grid.minor = element_blank(), 
      panel.spacing = unit(0.5, "lines"), 
      plot.background = element_blank(), 
      plot.margin = unit(c(0.3,  0.3, 0.3, 0.3), "lines"),
      axis.line.x = element_line(color="black", size = 0.5),
      axis.line.y = element_line(color="black", size = 0.5)
    )
}
#color
Features = c('#deebf7','#9ecae1','#6baed6','#4292c6','#08519c','#08306b',
             '#fee6ce','#fdae6b','#fd8d3c','#f16913','#a63603','#7f2704',
             '#f0f0f0','#bdbdbd','#969696','#737373','#252525','#000000',
             '#efedf5','#bcbddc','#9e9ac8','#807dba','#54278f','#3f007d')
```

```{r}
time = '2500';
pilot_version = "70levels_V323Fs";
pilot_versionD2 = "70levels_V323FsD2";

dataPath = '/Volumes/Macintosh HD/Users/Pam_sf_wang/Documents/Perceptual_learning_project/Calibration/Calibration_analysis/Prolific_analysis/70levels/';

data_new_fnameD1 = paste0("Prolific_",pilot_version,"_",time,".csv")
data_new_fnameD2 = paste0("Prolific_",pilot_versionD2,"_",time,".csv")
#load data
totalDataD1 = read.csv(paste0(dataPath,data_new_fnameD1),header = T)
totalDataD1 = totalDataD1[,-1]
totalDataD1 = mutate(totalDataD1, Day = "D1")

totalDataD2 = read.csv(paste0(dataPath,data_new_fnameD2),header = T)
totalDataD2 = totalDataD2[,-1]
totalDataD2 = mutate(totalDataD2, Day = "D2")

totalData = rbind(totalDataD1,totalDataD2)

d_p_thre = 5/100
trial_thre = 95/100
age_thre = 35
```


##Identify and remove outliers 
```{r}
summarize = dplyr::summarize
#check basic performance -- remove non-responding subjects
temp = totalData %>% group_by(subID,feature_index,Day) %>% summarize(num_noresponses= sum(keys==-1), trialNum = length(subID), no_resp = sum(keys==-1)/trialNum)
head(temp)
  

###quantile: sample quantiles corresponding to the given probabilities
summary(temp$no_resp)
noresp_thre = quantile(temp$no_resp,prob = trial_thre)
sprintf("the last 5percent of non-resp rate (threshold for excluding subjects): %f",noresp_thre)

ggplot(temp, aes(y= no_resp, x= subID,color = as.factor(feature_index)))+
  geom_point()+
  geom_hline(yintercept=noresp_thre, linetype="dashed", color = "red", size=0.5)+
  labs(title="No responses", x ="subjuect ID", y = "number of no responses")+
  plotformat

ggplot(temp, aes(y= no_resp, x= feature_index,color = as.factor(feature_index)))+
  geom_boxplot(fill = "white",lwd = 1)+
  geom_jitter(width=0.2,alpha = 0.5)+
  geom_hline(yintercept=noresp_thre, linetype="dashed", color = "red", size=0.5)+
  labs(title="No responses", x ="subjuect ID", y = "number of no responses")+
  plotformat

  
#no response subjects
removeSub = temp$subID[temp$no_resp>=noresp_thre]
totalData = totalData%>%filter(!subID %in% removeSub)
totalData = mutate(totalData, subID = as.factor(subID))

sprintf("remove no response subjects: %i; remain subjects %i",length(removeSub),length(unique(totalData$subID)))
removeSub
```

## Add conditions
```{r}
summarize = dplyr::summarize
#trial conditions: different:D; same:S (same as keys)
totalData$SameDiff = NA;
totalData$SameDiff[totalData$Fimg==totalData$Simg]="S";
totalData$SameDiff[totalData$Fimg!=totalData$Simg]="D";
  
totalData$feature_index = as.factor(totalData$feature_index)
  
#trial conditions: level
totalData$level_diff = as.factor(abs(totalData$Fimg-totalData$Simg))

#pair identity
temp = data.frame()
for (irow in 1:dim(totalData)[1]){
  tempPair = sort(c(totalData$Fimg[irow],totalData$Simg[irow]))
  tempName = paste(tempPair,collapse = "_")
  tempName = paste(tempName,totalData$feature_index[irow],sep="_F")
  totalData$PairIdentity[irow]=tempName
  rm(tempName)
}
```

##Task structure
```{r}
temptrialNumbers=totalData %>%group_by(subID,feature_index,SameDiff,Day)%>%summarize(num_same = length(SameDiff))
head(temptrialNumbers)
temptrialNumbers %>%group_by(feature_index,Day)%>%summarize(num_sub = length(subID)/2)
```

###overall dp
```{r}
basic = totalData %>% filter(keys>=0, run==3,Day=="D2")%>% group_by(subID)%>% summarize(
  hit = sum(keys==1&SameDiff=="S"), 
  fa= sum(keys==1&SameDiff=="D"), 
  cr = sum(keys==0&SameDiff=="D"),
  miss = sum(keys==0&SameDiff=="S"),
  HitRate =sum(keys==1&SameDiff=="S")/sum(SameDiff=="S"), 
  FARate = sum(keys==1&SameDiff=="D")/sum(SameDiff=="D"), 
  CRRate = sum(keys==0&SameDiff=="D")/sum(SameDiff=="D"),
  MissRate = sum(keys==0&SameDiff=="S")/sum(SameDiff=="S"), 
  adjFARate = 1/(2*sum(SameDiff=="D")),
  adjHitRate = 1-(1/(2*sum(SameDiff=="S"))))

basic$FARate[basic$FARate==0]=basic$adjFARate[basic$FARate==0]
basic$HitRate[basic$HitRate[!is.na(basic$HitRate)]==1]=basic$adjHitRate[basic$HitRate[!is.na(basic$HitRate)]==1]

row_index = basic$CRRate==1 & basic$MissRate==1
basic$FARate[row_index]=NA
basic$HitRate[row_index]=NA
basic$adjFARate[row_index]=NA
basic$adjHitRate[row_index]=NA

row_index = basic$CRRate==0 & basic$MissRate==0
basic$FARate[row_index]=NA
basic$HitRate[row_index]=NA
basic$adjFARate[row_index]=NA
basic$adjHitRate[row_index]=NA

basic = mutate(basic, d_p = qnorm(HitRate)-qnorm(FARate))

#d-p
ggplot(basic, aes(x = subID, y = d_p, color = as.factor(subID)))+
  geom_point(size=3)+
  labs(title="d prime", x = "subject", y = "d prime")+
  plotformat
```

####low-dp
```{r}
removedp_thre = quantile(basic$d_p[!is.na(basic$d_p)],prob = d_p_thre)
removeSubdp = basic$subID[basic$d_p<removedp_thre | is.na(basic$d_p)]
sprintf("low d-prime %f. subjects: %i",removedp_thre,length(removeSubdp))

##remove low dp 3rd run
num_lowdp = totalData %>% filter(subID %in% as.character(removeSubdp)) %>% group_by(feature_index) %>% summarize(num_trial = length(unique(subID)))
num_lowdp

totalData = totalData%>% filter(!subID %in% removeSubdp)
```

###separate by run
```{r}
basicLevelFeature = totalData %>% group_by(subID,level_diff,feature_index,run,Day)%>% 
summarize(  accuracy = sum(accuracy)/length(subID),
            hit = sum(keys==1&SameDiff=="S"), 
            fa= sum(keys==1&SameDiff=="D"), 
            cr = sum(keys==0&SameDiff=="D"),
            miss = sum(keys==0&SameDiff=="S"),
            HitRate =sum(keys==1&SameDiff=="S")/sum(SameDiff=="S"), 
            FARate = sum(keys==1&SameDiff=="D")/sum(SameDiff=="D"), 
            CRRate = sum(keys==0&SameDiff=="D")/sum(SameDiff=="D"),
            MissRate = sum(keys==0&SameDiff=="S")/sum(SameDiff=="S"))  #filter(keys>=0)%>%

  
  ggplot(filter(basicLevelFeature,feature_index==0), aes(x=level_diff,y=accuracy,group = level_diff,color=subID))+
    geom_boxplot(fill = "white",lwd = 1)+
    geom_jitter(width=0.2,alpha = 0.5)+
    labs(title="Feauture 00", x = "level diff", y = "accuracy")+
    ylim(0,1)+
    facet_wrap(Day~run)+
    plotformat
  
    ggplot(filter(basicLevelFeature,feature_index==1), aes(x=level_diff,y=accuracy,group = level_diff,color=subID))+
    geom_boxplot(fill = "white",lwd = 1)+
    geom_jitter(width=0.2,alpha = 0.5)+
    labs(title="Feauture 01", x = "level diff", y = "accuracy")+
    ylim(0,1)+
    facet_wrap(Day~run)+
    plotformat
    
    ggplot(filter(basicLevelFeature,feature_index==2), aes(x=level_diff,y=accuracy,group = level_diff,color=subID))+
    geom_boxplot(fill = "white",lwd = 1)+
    geom_jitter(width=0.2,alpha = 0.5)+
    labs(title="Feauture 02", x = "level diff", y = "accuracy")+
    ylim(0,1)+
    facet_wrap(Day~run)+
    plotformat
      
 ggplot(filter(basicLevelFeature,feature_index==3), aes(x=level_diff,y=accuracy,group = level_diff,color=subID))+
    geom_boxplot(fill = "white",lwd = 1)+
    geom_jitter(width=0.2,alpha = 0.5)+
    labs(title="Feauture 03", x = "level diff", y = "accuracy")+
    ylim(0,1)+
    facet_wrap(Day~run)+
    plotformat
    
```

## Compare level diff 1
```{r}
tempF0 = totalData %>%filter(Day=="D2",feature_index==0) 
tempF0list = unique(tempF0$subID)
basicLevelFeatureRepeatF0 = basicLevelFeature %>%filter(feature_index==0,subID %in% tempF0list )

tempF0 = totalData %>%filter(Day=="D2",feature_index==1) 
tempF0list = unique(tempF0$subID)
basicLevelFeatureRepeatF1 = basicLevelFeature %>%filter(feature_index==1,subID %in% tempF0list )

tempF0 = totalData %>%filter(Day=="D2",feature_index==2) 
tempF0list = unique(tempF0$subID)
basicLevelFeatureRepeatF2 = basicLevelFeature %>%filter(feature_index==2,subID %in% tempF0list )

tempF0 = totalData %>%filter(Day=="D2",feature_index==3) 
tempF0list = unique(tempF0$subID)
basicLevelFeatureRepeatF3 = basicLevelFeature %>%filter(feature_index==3,subID %in% tempF0list )

basicLevelFeatureRepeat = rbind(basicLevelFeatureRepeatF0,basicLevelFeatureRepeatF1,basicLevelFeatureRepeatF2,basicLevelFeatureRepeatF3)
anovaData = filter(basicLevelFeatureRepeat, level_diff==1,run==3)
anovaData= mutate(anovaData, subID = as.factor(subID), Day = as.factor(Day))
anovatestDays = ezANOVA(data = anovaData,
                        dv = .(accuracy),
                        wid = .(subID),
                        within = .(Day))

anovatestDays

feature0 = filter(basicLevelFeatureRepeatF0,feature_index==0, level_diff==1,run==3)
ggplot(feature0, aes(x=Day,y=accuracy,group = subID, color=subID))+
labs(title="Feauture 00", x = "day", y = "accuracy")+
ylim(0,1)+
geom_point()+
geom_line()+
plotformat

t.test(filter(feature0,Day=="D1")$accuracy,filter(feature0,Day=="D2")$accuracy,paired=TRUE)

##
feature1 = filter(basicLevelFeatureRepeatF1,feature_index==1, level_diff==1,run==3)
ggplot(feature1, aes(x=Day,y=accuracy,group = subID, color=subID))+
labs(title="Feauture 01", x = "day", y = "accuracy")+
ylim(0,1)+
geom_point()+
geom_line()+
plotformat

sublist = filter(feature1,Day=="D2")$subID
t.test(filter(feature1,Day=="D1",subID %in% sublist)$accuracy,filter(feature1,Day=="D2")$accuracy,paired=TRUE)
##
feature2 = filter(basicLevelFeatureRepeatF2,feature_index==2, level_diff==1,run==3 )
ggplot(feature2, aes(x=Day,y=accuracy,group = subID, color=subID))+
labs(title="Feauture 02", x = "day", y = "accuracy")+
ylim(0,1)+
geom_point()+
geom_line()+
plotformat

sublist = filter(feature2,Day=="D2")$subID
t.test(filter(feature2,Day=="D1",subID %in% sublist)$accuracy,filter(feature2,Day=="D2")$accuracy,paired=TRUE)

##
feature3 = filter(basicLevelFeatureRepeatF3,feature_index==3, level_diff==1,run==3)
ggplot(feature3, aes(x=Day,y=accuracy,group = subID, color=subID))+
labs(title="Feauture 03", x = "day", y = "accuracy")+
ylim(0,1)+
geom_point()+
geom_line()+
plotformat

sublist = filter(feature3,Day=="D2")$subID
t.test(filter(feature3,Day=="D1",subID %in% sublist)$accuracy,filter(feature3,Day=="D2")$accuracy,paired=TRUE)
```
  
  
  
