---
title: 'Prolific Calibration V323Fs Day2 6pics - 2500ms analysis'
output:
github_document:
toc: yes
toc_float: yes
---

```{r, message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(plyr)
library(tidyr)
library(ggplot2)
library(stringr)
library(lme4)
library(lmerTest)
library(ez)
```

```{r}
#plotting format
plotformat = theme(plot.title = element_text(face="bold",size = 17,hjust = 0.5),axis.title = element_text(face = "bold",size =15), axis.text.x = element_text(size=12), axis.title.y=element_text(size=14))+theme_bw()

theme_facet = function(base_size = 14, base_family = "Helvetica") {
  # Starts with theme_grey and then modify some parts
  theme_bw(base_size = base_size, base_family = base_family) %+replace%
    theme(
      strip.background = element_blank(),
      strip.text.x = element_text(size = 10),
      strip.text.y = element_text(size = 10),
      axis.text.x = element_blank(),
      axis.text.y = element_text(size=12,hjust=1),
      axis.ticks =  element_blank(), #element_line(colour = "black"), 
      axis.title.x= element_text(size=12),
      axis.title.y= element_text(size=12,angle=90),
      panel.background = element_blank(), 
      panel.border =element_blank(), 
      panel.grid.minor = element_blank(), 
      panel.spacing = unit(0.5, "lines"), 
      plot.background = element_blank(), 
      plot.margin = unit(c(0.3,  0.3, 0.3, 0.3), "lines"),
      axis.line.x = element_line(color="black", size = 0.5),
      axis.line.y = element_line(color="black", size = 0.5)
    )
}
#color
Features = c('#deebf7','#9ecae1','#6baed6','#4292c6','#08519c','#08306b',
             '#fee6ce','#fdae6b','#fd8d3c','#f16913','#a63603','#7f2704',
             '#f0f0f0','#bdbdbd','#969696','#737373','#252525','#000000',
             '#efedf5','#bcbddc','#9e9ac8','#807dba','#54278f','#3f007d')
```

```{r}
time = '2500';
pilot_version = "70levels_V323FsD2";
dataPath = '/Volumes/Macintosh HD/Users/Pam_sf_wang/Documents/Perceptual_learning_project/Calibration/Calibration_analysis/Prolific_analysis/70levels/';
TotaltrialNum = 231


data_new_fname = paste0("Prolific_",pilot_version,"_",time,".csv")
demographic_new_fname = paste0("Prolific_",pilot_version,"_demographic",time,".csv")
postsurvey_new_fname = paste0("Prolific_",pilot_version,"_postsurvey",time,".csv")

postsurvey_dp_fname = paste0("Prolific_",pilot_version,"_survey_dp",time,".csv")

d_p_thre = 1/100
trial_thre = 99/100
age_thre = 35
```

##load data
```{r}
totalData = read.csv(paste0(dataPath,data_new_fname),header = T)
totalData = totalData[,-1]
demographic_information = read.csv(paste0(dataPath,demographic_new_fname),header = T)
postsurvey = read.csv(paste0(dataPath,postsurvey_new_fname),header = T)
```

  
##Identify and remove outliers 
```{r}
summarize = dplyr::summarize
#check basic performance -- remove non-responding subjects
temp = totalData %>% group_by(subID,feature_index) %>% summarize(num_noresponses= sum(keys==-1), trialNum = length(subID), no_resp = sum(keys==-1)/trialNum)
sprintf("total trial number: %i; Number of subjects %i",temp$trialNum[1],dim(temp)[1])
head(temp)
  

###quantile: sample quantiles corresponding to the given probabilities
summary(temp$no_resp)
noresp_thre = quantile(temp$no_resp,prob = trial_thre)
sprintf("the last 5percent of non-resp rate (threshold for excluding subjects): %f",noresp_thre)

ggplot(temp, aes(y= no_resp, x= subID,color = as.factor(feature_index)))+
  geom_point()+
  geom_hline(yintercept=noresp_thre, linetype="dashed", color = "red", size=0.5)+
  labs(title="No responses", x ="subjuect ID", y = "number of no responses")+
  plotformat

ggplot(temp, aes(y= no_resp, x= feature_index,color = as.factor(feature_index)))+
  geom_boxplot(fill = "white",lwd = 1)+
  geom_jitter(width=0.2,alpha = 0.5)+
  geom_hline(yintercept=noresp_thre, linetype="dashed", color = "red", size=0.5)+
  labs(title="No responses", x ="subjuect ID", y = "number of no responses")+
  plotformat

  
#no response subjects
removeSub = temp$subID[temp$no_resp>=noresp_thre | temp$trialNum<TotaltrialNum]
totalData = totalData%>%filter(!subID %in% removeSub)
totalData = mutate(totalData, subID = as.factor(subID))
demographic_information = demographic_information%>%filter(!SubID %in%removeSub)

sprintf("remove no response subjects: %i; remain subjects %i",length(removeSub),length(unique(totalData$subID)))
removeSub
```
  
##Demographic information
```{r}
genderCount = table(demographic_information$Gender)
EthnicityCount = table(demographic_information$Ethnicity)
RaceCount = table(demographic_information$Race)
genderCount
EthnicityCount
RaceCount
  
summary(demographic_information$Age)
  ggplot(demographic_information, aes(demographic_information$Age)) + 
    geom_histogram()+
    geom_vline(xintercept=median(demographic_information$Age), linetype="dashed", color = "red", size=0.5)+
    #geom_vline(xintercept=mean(demographic_information$Age), linetype="dashed", color = "blue", size=0.5)+
    labs(title = "Age Distribution",x = "age", y = "counts")+
    plotformat
```
  
##Restrict age 
```{r}
#select right age
remainSub = demographic_information$SubID[is.na(demographic_information$Age) | demographic_information$Age<=age_thre]
demographic_information_remain = filter(demographic_information,SubID%in%remainSub)
  
summary(demographic_information_remain$Age)
ggplot(demographic_information_remain, aes(Age)) + 
  geom_histogram()+
  geom_vline(xintercept=median(demographic_information_remain$Age), linetype="dashed", color = "red", size=0.5)+
  #geom_vline(xintercept=mean(demographic_information$Age), linetype="dashed", color = "blue", size=0.5)+
  labs(title = "Age Distribution",x = "age", y = "counts")+
  plotformat
  
genderCount = table(demographic_information_remain$Gender)
EthnicityCount = table(demographic_information_remain$Ethnicity)
RaceCount = table(demographic_information_remain$Race)
genderCount
EthnicityCount
RaceCount
  
#remove subjects who are outside of the age range
removeSubAge = demographic_information$SubID[!is.na(demographic_information$Age) & demographic_information$Age>age_thre]
totalData = totalData %>%filter(subID %in%remainSub)
sprintf("remove over aged subejcts %i; remain subjects: %i", length(removeSubAge),length(unique(totalData$subID)))

```
  
  
## Add conditions
```{r}
summarize = dplyr::summarize
#trial conditions: different:D; same:S (same as keys)
totalData$SameDiff = NA;
totalData$SameDiff[totalData$Fimg==totalData$Simg]="S";
totalData$SameDiff[totalData$Fimg!=totalData$Simg]="D";
  
totalData$feature_index = as.factor(totalData$feature_index)
  
#trial conditions: level
totalData$level_diff = as.factor(abs(totalData$Fimg-totalData$Simg))

#pair identity
temp = data.frame()
for (irow in 1:dim(totalData)[1]){
  tempPair = sort(c(totalData$Fimg[irow],totalData$Simg[irow]))
  tempName = paste(tempPair,collapse = "_")
  tempName = paste(tempName,totalData$feature_index[irow],sep="_F")
  totalData$PairIdentity[irow]=tempName
  rm(tempName)
}
```
  

##Task structure
```{r}
temptrialNumbers=totalData %>%group_by(subID,feature_index,SameDiff)%>%summarize(num_same = length(SameDiff))
head(temptrialNumbers)

temptrialNumbers %>%group_by(feature_index)%>%summarize(num_sub = length(subID)/2)

```
##Behavior analysis
```{r}
summarize = dplyr::summarize
#over all performance
basic = totalData %>% filter(keys>=0, run==3)%>% group_by(subID)%>% summarize(
  hit = sum(keys==1&SameDiff=="S"), 
  fa= sum(keys==1&SameDiff=="D"), 
  cr = sum(keys==0&SameDiff=="D"),
  miss = sum(keys==0&SameDiff=="S"),
  HitRate =sum(keys==1&SameDiff=="S")/sum(SameDiff=="S"), 
  FARate = sum(keys==1&SameDiff=="D")/sum(SameDiff=="D"), 
  CRRate = sum(keys==0&SameDiff=="D")/sum(SameDiff=="D"),
  MissRate = sum(keys==0&SameDiff=="S")/sum(SameDiff=="S"), 
  adjFARate = 1/(2*sum(SameDiff=="D")),
  adjHitRate = 1-(1/(2*sum(SameDiff=="S"))))

basic$FARate[basic$FARate==0]=basic$adjFARate[basic$FARate==0]
basic$HitRate[basic$HitRate[!is.na(basic$HitRate)]==1]=basic$adjHitRate[basic$HitRate[!is.na(basic$HitRate)]==1]

row_index = basic$CRRate==1 & basic$MissRate==1
basic$FARate[row_index]=NA
basic$HitRate[row_index]=NA
basic$adjFARate[row_index]=NA
basic$adjHitRate[row_index]=NA

row_index = basic$CRRate==0 & basic$MissRate==0
basic$FARate[row_index]=NA
basic$HitRate[row_index]=NA
basic$adjFARate[row_index]=NA
basic$adjHitRate[row_index]=NA

basic = mutate(basic, d_p = qnorm(HitRate)-qnorm(FARate))

#Plotting
basic_longform = gather(basic, response_type, number_resp, HitRate,FARate,CRRate,MissRate)
head(basic_longform)
ggplot(basic_longform, aes(x = response_type, y = number_resp, color = response_type))+
  geom_boxplot(fill = "white",lwd = 1)+
  geom_jitter(width=0.2,alpha = 0.5)+
  labs(title="Proportaion response type", x = "response type", y = "proportion")+
  plotformat
  
#d-p
ggplot(basic, aes(x = subID, y = d_p, color = as.factor(subID)))+
  geom_point(size=3)+
  labs(title="d prime", x = "subject", y = "d prime")+
  plotformat

ggplot(basic,aes(d_p))+
  geom_histogram()+
  labs(title="d prime histogram", x = "d prime", y = "counts")+
  plotformat

#bad d_p
```

####check subjects with low d-p & save survey data
```{r}  
removedp_thre = quantile(basic$d_p[!is.na(basic$d_p)],prob = d_p_thre)
removeSubdp = basic$subID[basic$d_p<removedp_thre | is.na(basic$d_p)]
sprintf("low d-prime %f. subjects: %i",removedp_thre,length(removeSubdp))

remainSubdp = basic$subID[basic$d_p>d_p_thre]
sprintf("pass d-prim threshould: %i", length(remainSubdp))
#sprintf("remove d prime lower than %f. Sequence 01 remain subjects: %i; sequence 02 remain subjects: %i",d_p_thre, #length(remain_dp_s1),length(remain_dp_s2))

for (irow in 1:dim(postsurvey)[1]){
  for (irow_basic in 1:dim(basic)[1]){
    if (postsurvey$SubID[irow]==basic$subID[irow_basic]){
      postsurvey$basic_id[irow] = as.character(basic$subID[irow_basic])
      postsurvey$d_p[irow] = basic$d_p[irow_basic]
      postsurvey$feature[irow] = unique(totalData$feature_index[totalData$subID==postsurvey$SubID[irow]])
    }
  }
}

write.csv(postsurvey, file = paste0(postsurvey_dp_fname,".csv"))

##remove low dp 3rd run
num_lowdp = totalData %>% filter(subID %in% as.character(removeSubdp)) %>% group_by(feature_index) %>% summarize(num_trial = length(unique(subID)))
num_lowdp

totalData = totalData%>% filter(!subID %in% removeSubdp)
```

###by features -- within Features
```{r}
summarize = dplyr::summarize
##########
basicFeature = totalData  %>%group_by(subID,feature_index)%>% summarize(
            hit = sum(keys==1&SameDiff=="S"), 
            fa= sum(keys==1&SameDiff=="D"), 
            cr = sum(keys==0&SameDiff=="D"),
            miss = sum(keys==0&SameDiff=="S"),
            HitRate =sum(keys==1&SameDiff=="S")/sum(SameDiff=="S"), 
            FARate = sum(keys==1&SameDiff=="D")/sum(SameDiff=="D"), 
            CRRate = sum(keys==0&SameDiff=="D")/sum(SameDiff=="D"),
            MissRate = sum(keys==0&SameDiff=="S")/sum(SameDiff=="S"), 
            adjFARate = 1/(2*sum(SameDiff=="D")),
            adjHitRate = 1-(1/(2*sum(SameDiff=="S"))))

basicFeature$FARate[basicFeature$FARate==0]=basicFeature$adjFARate[basicFeature$FARate==0]
basicFeature$HitRate[basicFeature$HitRate[!is.na(basicFeature$HitRate)]==1]=basicFeature$adjHitRate[basicFeature$HitRate[!is.na(basicFeature$HitRate)]==1]

row_index = basicFeature$CRRate==1 & basicFeature$MissRate==1
basicFeature$FARate[row_index]=NA
basicFeature$HitRate[row_index]=NA
basicFeature$adjFARate[row_index]=NA
basicFeature$adjHitRate[row_index]=NA

row_index = basicFeature$CRRate==0 & basicFeature$MissRate==0
basicFeature$FARate[row_index]=NA
basicFeature$HitRate[row_index]=NA
basicFeature$adjFARate[row_index]=NA
basicFeature$adjHitRate[row_index]=NA

basicFeature = mutate(basicFeature, d_p = qnorm(HitRate)-qnorm(FARate))

###
basicFeature_longform = gather(basicFeature, response_type, number_resp, HitRate,FARate,CRRate,MissRate)
head(basicFeature_longform)
  
ggplot(basicFeature_longform, aes(x = response_type, y = number_resp, color = response_type))+
  geom_boxplot(fill = "white",lwd = 1)+
  geom_jitter(width=0.2,alpha = 0.5)+
  facet_wrap(~feature_index)+
  labs(title="Proportaion response type by feature", x = "response type", y = "proportion")+
  theme_facet()

ggplot(basicFeature, aes(x = feature_index, y = d_p, group = feature_index, color = feature_index))+
  geom_boxplot(fill = "white",lwd = 1)+
  geom_jitter(width=0.2,alpha = 0.5)+
  plotformat

#ggplot(basicFeature, aes(x = subID, y = d_p, group = feature_index, color = feature_index))+
#  geom_point(size=3)+
#  plotformat
```

####stats
```{r}
basicFeature$feature_index[is.infinite(basicFeature$d_p)]
basicFeature$subID[is.infinite(basicFeature$d_p)]
feature_anova = aov(d_p~feature_index,basicFeature)
summary(feature_anova)
```

###by features by runs -- within Features
```{r}
summarize = dplyr::summarize
##########
basicFeature = totalData  %>%group_by(subID,feature_index,run)%>% summarize(
            hit = sum(keys==1&SameDiff=="S"), 
            fa= sum(keys==1&SameDiff=="D"), 
            cr = sum(keys==0&SameDiff=="D"),
            miss = sum(keys==0&SameDiff=="S"),
            HitRate =sum(keys==1&SameDiff=="S")/sum(SameDiff=="S"), 
            FARate = sum(keys==1&SameDiff=="D")/sum(SameDiff=="D"), 
            CRRate = sum(keys==0&SameDiff=="D")/sum(SameDiff=="D"),
            MissRate = sum(keys==0&SameDiff=="S")/sum(SameDiff=="S"), 
            adjFARate = 1/(2*sum(SameDiff=="D")),
            adjHitRate = 1-(1/(2*sum(SameDiff=="S"))))

basicFeature$FARate[basicFeature$FARate==0]=basicFeature$adjFARate[basicFeature$FARate==0]
basicFeature$HitRate[basicFeature$HitRate[!is.na(basicFeature$HitRate)]==1]=basicFeature$adjHitRate[basicFeature$HitRate[!is.na(basicFeature$HitRate)]==1]

row_index = basicFeature$CRRate==1 & basicFeature$MissRate==1
basicFeature$FARate[row_index]=NA
basicFeature$HitRate[row_index]=NA
basicFeature$adjFARate[row_index]=NA
basicFeature$adjHitRate[row_index]=NA

row_index = basicFeature$CRRate==0 & basicFeature$MissRate==0
basicFeature$FARate[row_index]=NA
basicFeature$HitRate[row_index]=NA
basicFeature$adjFARate[row_index]=NA
basicFeature$adjHitRate[row_index]=NA

basicFeature = mutate(basicFeature, d_p = qnorm(HitRate)-qnorm(FARate))
###
ggplot(basicFeature, aes(x = feature_index, y = d_p, group = feature_index, color = feature_index))+
  geom_boxplot(fill = "white",lwd = 1)+
  geom_jitter(width=0.2,alpha = 0.5)+
  facet_wrap(~run)+
  plotformat

#ggplot(basicFeature, aes(x = subID, y = d_p, group = feature_index, color = feature_index))+
#  geom_point(size=3)+
#  plotformat
```
####stats
```{r}
basicFeature_run3 = basicFeature %>% filter(run==3, !is.infinite(d_p))
anovaFeature3rdRun = aov(d_p~feature_index,basicFeature_run3)
summary(anovaFeature3rdRun)

anovaFeature3rdRunF123 = aov(d_p~feature_index,filter(basicFeature_run3,feature_index %in% c(1,2,3)))
summary(anovaFeature3rdRunF123)

anovaFeature3rdRunF023 = aov(d_p~feature_index,filter(basicFeature_run3,feature_index %in% c(0,2,3)))
summary(anovaFeature3rdRunF023)

summarize = dplyr::summarize
compareFeature3rdRun = basicFeature  %>%filter(run==3,!is.infinite(d_p)) %>% group_by(feature_index) %>%summarize(meanD_p = mean(d_p),std =sd(d_p),med = median(d_p) )
compareFeature3rdRun

#top 10 subjects
topdp = quantile(basicFeature$d_p,90/100)
tempBasicFeature = basicFeature %>% filter(run==3)
top10 = tempBasicFeature %>%filter(d_p>=topdp)
top10
```

### within a feature: levels
```{r}
summarize = dplyr::summarize

basicLevel = totalData %>% filter(keys>=0)%>% group_by(subID,level_diff)%>% 
summarize(
            hit = sum(keys==1&SameDiff=="S"), 
            fa= sum(keys==1&SameDiff=="D"), 
            cr = sum(keys==0&SameDiff=="D"),
            miss = sum(keys==0&SameDiff=="S"),
            HitRate =sum(keys==1&SameDiff=="S")/sum(SameDiff=="S"), 
            FARate = sum(keys==1&SameDiff=="D")/sum(SameDiff=="D"), 
            CRRate = sum(keys==0&SameDiff=="D")/sum(SameDiff=="D"),
            MissRate = sum(keys==0&SameDiff=="S")/sum(SameDiff=="S"))

####
basicLevel_longform = gather(basicLevel, response_type, resp_rate, HitRate,FARate,CRRate,MissRate)
head(basicLevel_longform)
  
ggplot(basicLevel_longform, aes(x = response_type, y = resp_rate, color = response_type))+
  geom_boxplot(fill = "white",lwd = 1)+
  geom_jitter(width=0.2,alpha = 0.5)+
  facet_wrap(~level_diff,nrow = 1)+
  labs(title="Proportaion response type by difficulty level", x = "response type", y = "proportion")+
  theme_facet()
  
###########
basicLevelFeature = totalData %>% filter(keys>=0)%>%group_by(subID,level_diff,feature_index)%>% 
summarize(  accuracy = sum(accuracy)/length(subID),
            hit = sum(keys==1&SameDiff=="S"), 
            fa= sum(keys==1&SameDiff=="D"), 
            cr = sum(keys==0&SameDiff=="D"),
            miss = sum(keys==0&SameDiff=="S"),
            HitRate =sum(keys==1&SameDiff=="S")/sum(SameDiff=="S"), 
            FARate = sum(keys==1&SameDiff=="D")/sum(SameDiff=="D"), 
            CRRate = sum(keys==0&SameDiff=="D")/sum(SameDiff=="D"),
            MissRate = sum(keys==0&SameDiff=="S")/sum(SameDiff=="S"))
  basicLevelFeature_longform = gather(basicLevelFeature, response_type, resp_rate, HitRate,FARate,CRRate,MissRate)
  head(basicLevelFeature_longform)
  
  ggplot(basicLevelFeature, aes(x=level_diff,y=accuracy,color = feature_index))+
    geom_boxplot(fill = "white",lwd = 1)+
    plotformat
  
  ggplot(filter(basicLevelFeature,feature_index==0), aes(x=level_diff,y=accuracy))+
    geom_boxplot(fill = "white",lwd = 1)+
    geom_jitter(width=0.2,alpha = 0.5)+
    labs(title="Feauture 00", x = "level diff", y = "accuracy")+
    ylim(0,1)+
    plotformat
  
  ggplot(filter(basicLevelFeature,feature_index==1), aes(x=level_diff,y=accuracy))+
    geom_boxplot(fill = "white",lwd = 1)+
    geom_jitter(width=0.2,alpha = 0.5)+
    labs(title="Feauture 01", x = "level diff", y = "accuracy")+
    ylim(0,1)+
    plotformat
  
  ggplot(filter(basicLevelFeature,feature_index==2), aes(x=level_diff,y=accuracy))+
    geom_boxplot(fill = "white",lwd = 1)+
    geom_jitter(width=0.2,alpha = 0.5)+
    labs(title="Feauture 02", x = "level diff", y = "accuracy")+
    ylim(0,1)+
    plotformat
  
  ggplot(filter(basicLevelFeature,feature_index==3), aes(x=level_diff,y=accuracy))+
    geom_boxplot(fill = "white",lwd = 1)+
    geom_jitter(width=0.2,alpha = 0.5)+
    labs(title="Feauture 03", x = "level diff", y = "accuracy")+
    ylim(0,1)+
    plotformat
```


####stats
```{r}
anovaFeatureLevel = aov(accuracy~feature_index+level_diff,basicLevelFeature)
summary(anovaFeatureLevel)

anovaFeatureLevelF123 = aov(accuracy~feature_index+level_diff,filter(basicLevelFeature,feature_index %in% c(1,2,3)))
summary(anovaFeatureLevelF123)

anovaFeatureLevelF023 = aov(accuracy~feature_index+level_diff,filter(basicLevelFeature,feature_index %in% c(0,2,3)))
summary(anovaFeatureLevelF023)


summarize = dplyr::summarize
compareFeatures = basicLevelFeature  %>%group_by(feature_index,level_diff) %>%summarize(meanAccuracy = mean(accuracy),std =sd(accuracy) )
compareFeatures
```
###separate by run
```{r}
basicLevelFeature = totalData %>% group_by(subID,level_diff,feature_index,run)%>% 
summarize(  accuracy = sum(accuracy)/length(subID),
            hit = sum(keys==1&SameDiff=="S"), 
            fa= sum(keys==1&SameDiff=="D"), 
            cr = sum(keys==0&SameDiff=="D"),
            miss = sum(keys==0&SameDiff=="S"),
            HitRate =sum(keys==1&SameDiff=="S")/sum(SameDiff=="S"), 
            FARate = sum(keys==1&SameDiff=="D")/sum(SameDiff=="D"), 
            CRRate = sum(keys==0&SameDiff=="D")/sum(SameDiff=="D"),
            MissRate = sum(keys==0&SameDiff=="S")/sum(SameDiff=="S"))  #filter(keys>=0)%>%
  basicLevelFeature_longform = gather(basicLevelFeature, response_type, resp_rate, HitRate,FARate,CRRate,MissRate)
  head(basicLevelFeature_longform)
  
  ggplot(filter(basicLevelFeature,feature_index==0), aes(x=level_diff,y=accuracy,group = level_diff,color=subID))+
    geom_boxplot(fill = "white",lwd = 1)+
    geom_jitter(width=0.2,alpha = 0.5)+
    labs(title="Feauture 00", x = "level diff", y = "accuracy")+
    ylim(0,1)+
    facet_wrap(~run)+
    plotformat
  
  ggplot(filter(basicLevelFeature,feature_index==1), aes(x=level_diff,y=accuracy,group = level_diff,color=subID))+
    geom_boxplot(fill = "white",lwd = 1)+
    geom_jitter(width=0.2,alpha = 0.5)+
    labs(title="Feauture 01", x = "level diff", y = "accuracy")+
    ylim(0,1)+
    facet_wrap(~run)+
    plotformat
  
  ggplot(filter(basicLevelFeature,feature_index==2), aes(x=level_diff,y=accuracy,group = level_diff,color=subID))+
    geom_boxplot(fill = "white",lwd = 1)+
    geom_jitter(width=0.2,alpha = 0.5)+
    labs(title="Feauture 02", x = "level diff", y = "accuracy")+
    ylim(0,1)+
    facet_wrap(~run)+
    plotformat
  
  ggplot(filter(basicLevelFeature,feature_index==3), aes(x=level_diff,y=accuracy,group = level_diff,color=subID))+
    geom_boxplot(fill = "white",lwd = 1)+
    geom_jitter(width=0.2,alpha = 0.5)+
    labs(title="Feauture 03", x = "level diff", y = "accuracy")+
    ylim(0,1)+
    facet_wrap(~run)+
    plotformat
```


####stats
```{r}
anovaFeatureLevel = aov(accuracy~feature_index+level_diff+run,basicLevelFeature)
summary(anovaFeatureLevel)


anovaFeatureLevel3rdRun = aov(accuracy~feature_index+level_diff,filter(basicLevelFeature,run==3,feature_index%in%c(1,2,3)))
summary(anovaFeatureLevel3rdRun)

anovaFeatureLevel3rdRun = aov(accuracy~feature_index+level_diff,filter(basicLevelFeature,run==3,feature_index%in%c(0,2,3)))
summary(anovaFeatureLevel3rdRun)

anovaFeatureLevel3rdRun_same = aov(accuracy~feature_index,filter(basicLevelFeature,run==3, level_diff==0))
summary(anovaFeatureLevel3rdRun_same)
SameaccuracyF1 = filter(basicLevelFeature,feature_index==1,run==3 & level_diff==0)
SameaccuracyF2 = filter(basicLevelFeature,feature_index==2,run==3 & level_diff==0)
SameaccuracyF3 = filter(basicLevelFeature,feature_index==3,run==3 & level_diff==0)
t.test(SameaccuracyF1$accuracy,SameaccuracyF2$accuracy)
t.test(SameaccuracyF1$accuracy,SameaccuracyF3$accuracy)
t.test(SameaccuracyF2$accuracy,SameaccuracyF3$accuracy)

anovaFeatureLevel3rdRun_same = aov(accuracy~feature_index,filter(basicLevelFeature,run==3, level_diff==0,feature_index%in%c(1,2,3)))
summary(anovaFeatureLevel3rdRun_same)

anovaFeatureLevel3rdRun_same = aov(accuracy~feature_index,filter(basicLevelFeature,run==3, level_diff==0,feature_index%in%c(0,2,3)))
summary(anovaFeatureLevel3rdRun_same)

anovaFeatureLevel3rdRun_l01 = aov(accuracy~feature_index,filter(basicLevelFeature,run==3, level_diff==1))
summary(anovaFeatureLevel3rdRun_l01)

anovaFeatureLevel3rdRun_l01 = aov(accuracy~feature_index,filter(basicLevelFeature,run==3, level_diff==1,feature_index%in%c(0,2,3)))
summary(anovaFeatureLevel3rdRun_l01)

summarize = dplyr::summarize
compareFeatures = basicLevelFeature  %>% filter(run==3) %>% group_by(feature_index,level_diff) %>%summarize(meanAccuracy = mean(accuracy),std =sd(accuracy),med = median(accuracy) )
compareFeatures
```
